### PR TITLE
dependency updated to latest versions

### PR DESCRIPTION
**Pull request by wgarunap**
all third party dependencies updated to latest versions

### CODE REVIEW

**Comment by wgarunap** [comment]
@sorenmat please review this change

**Review by sorenmat — APPROVED** [review]

**Comment by sorenmat** [comment]
Could you please sign the commit?

**Comment by wgarunap** [comment]
@sorenmat please check, I have signed the commit

**Comment by sorenmat** [comment]
There still seem to be one unsigned commit :|
Also if you can squash the commits that would be awesome, thanks

**Comment by wgarunap** [comment]
Sorry about that, It's Fixed Now :)

**Comment by sorenmat** [comment]
Thanks, awesome work

**Pull request merged**
