### PR TITLE
Adapt to go 1.13 module support

### PR DESCRIPTION
**Pull request by blacksails**
The module support in go 1.13 has become quite awesome with the
introduction of module proxies which greatly speed up fetching of
dependencies, and also provides security with regards to tampering and
missing packages.

This PR adapts the project to rely solely on go modules without vendored
packages.

Changes:
- Make travis use go 1.13
- Make dockerfile build the project using a multistage build
- Add Makefile for build commands and tooling
- Remove Gopkg files and vendor directory
- Add go module file and sum file
- Add tools.go to include used tools in the module
- Adapt crd and rds provider to upgraded modules

We might want travis to simply run docker build and push.

### CODE REVIEW

**Comment by blacksails** [comment]
If you still would like to vendor the dependencies, I can change the PR to that.

**Comment by sorenmat** [comment]
I think we should split this up a little, quite a big PR :|
Do you think that would be possible?

**Comment by blacksails** [comment]
Yea possible but changes are very related. I will do some splitting.

**Comment by blacksails** [comment]
Closed in favor of #58 #59 #60

**Pull request closed without merging**
